# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    # Move from stupid loop to condition:healthy OR reconnect logic
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      #  http://127.0.0.1:8008/docs
      - "8008:8000"
    environment:
      - DATABASE_URL=postgresql://testuser:testpass@db:5432/main_db
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:8008/" ]
      interval: 1s
      timeout: 3s
      retries: 50
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=main_db

volumes:
  postgres_data: